set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 10
set -g status-position top
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux recarregado"
